name: intro-single-cell
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-seurat
  - r-tidyverse
  - r-vroom
  - r-devtools
  - r-harmony
  - bioconductor-singlecellexperiment
  - bioconductor-scdblfinder
  - bioconductor-singler
  - bioconductor-aucell
  - bioconductor-celldex
  - openssl=3.1.3
